services:
  - type: web
    name: Scam-Ratio
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - fromGroup: scam-ratio-production
      - key: JWT_SECRET
        generateValue: true